### ISSUE TITLE
Update new-editions-of-the-book.md with the new new book layout

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/edition-guide#164]
rust-2018/documentation/new-editions-of-the-book.md doesn't actually have what we're currently doing with the book.

I'm assigning this issue to myself.

We decided having first-edition, second-edition, and 2018-edition of the book available was confusing, so there's just the book now (i need to look up in what stable release this happened) and you can use version numbers in the url or install old versions of rust to get at the old versions of the book.

The book still lags behind the compiler because it takes time to incorporate new features and we also pin to a compiler version for print to keep things like error message output predictable.

We're in the final rounds of edits with nostarch for a second print edition that's updated for rust 2018; i'm hoping to fix this issue when that's all done and the print version is available so that i can mention that as well.

The index page needs to be updated too: https://github.com/rust-lang-nursery/edition-guide/blob/68c458b9b68edced39aebea60e672a22d4d50edf/src/rust-2018/documentation/index.md

**Comment by ehuss** [comment]
Closing per #232, this section has been removed.
