### ISSUE TITLE
Tracking issue for `?` on either Option or Result in the same function

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/edition-guide#169]
This section will need to be updated:

https://github.com/rust-lang-nursery/edition-guide/blame/1a7b200935c9a0c0964f928a92144e9e84e96d89/src/rust-2018/error-handling-and-panics/the-question-mark-operator-for-easier-error-handling.md#L117-L120

> One current restriction is that you cannot use `?` for both in the same function, as the return type needs to match the type you use `?` on. In the future, this restriction will be lifted.

I'm not sure what the right Rust tracking issue to link to is. Maybe https://github.com/rust-lang/rust/issues/31436 ?

**Comment by Nemo157** [comment]
`std::option::NoneError` which allows both links to https://github.com/rust-lang/rust/issues/42327.

**Comment by ehuss** [comment]
Closing per #232, this section has been removed.  Hopefully when those changes are stabilized it will trickle out to the right documentation.
