### ISSUE TITLE
Tracking issue for async/await

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/edition-guide#170]
Rust tracking issue: https://github.com/rust-lang/rust/issues/50547

Places that will need to be updated: 

- https://github.com/rust-lang-nursery/edition-guide/blame/68c458b9b68edced39aebea60e672a22d4d50edf/src/rust-2018/control-flow/index.md#L6 "The most notable of these *will* be [`async` and `await`][async_await]."
- The entire https://github.com/rust-lang-nursery/edition-guide/blob/68c458b9b68edced39aebea60e672a22d4d50edf/src/rust-2018/control-flow/async-await-for-easier-concurrency.md, which for now is a placeholder that says it'll be updated

**Comment by ehuss** [comment]
Closing per #232, this section has been removed.  Basic low-level details were added to the reference in https://github.com/rust-lang/reference/pull/635, and presumably the [async book](https://rust-lang.github.io/async-book/) will be the home for the primary user documentation.
