### ISSUE TITLE
Tracking issue for using impl Trait in more places

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/edition-guide#171]
Rust tracking issue: https://github.com/rust-lang/rust/issues/34511

Place that will need to be updated: https://github.com/rust-lang-nursery/edition-guide/blame/68c458b9b68edced39aebea60e672a22d4d50edf/src/rust-2018/trait-system/impl-trait-for-returning-complex-types-with-ease.md#L161-L168

> ### Using `impl Trait` in more places
> As previously mentioned, as a start, you will only be able to use `impl Trait` as the argument or return type of a free or inherent function. However, `impl Trait` can't be used inside implementations of traits, nor can it be used as the type of a let binding or inside a type alias. Some of these restrictions will eventually be lifted. For more information, see the [tracking issue on `impl Trait`](https://github.com/rust-lang/rust/issues/34511).

**Comment by ehuss** [comment]
Closing per #232, this section has been removed.  Hopefully has new language changes are stabilized, other documentation will get updated.
