### ISSUE TITLE
Tracking issue for more slice patterns

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/edition-guide#172]
Rust tracking issue: https://github.com/rust-lang/rust/issues/23121

Place that will need to be updated: https://github.com/rust-lang-nursery/edition-guide/blame/68c458b9b68edced39aebea60e672a22d4d50edf/src/rust-2018/slice-patterns.md#L86-L91

> ### In the pipeline
>
> [the tracking issue]: https://github.com/rust-lang/rust/issues/23121
>
> When it comes to slice patterns, more advanced forms are planned but
have not been stabilized yet. To learn more, follow [the tracking issue].

**Comment by Centril** [comment]
New tracking issue is https://github.com/rust-lang/rust/issues/62254.

**Comment by shepmaster** [comment]
Proposed stabilization PR at https://github.com/rust-lang/rust/pull/67712

**Comment by ehuss** [comment]
Closing per #232, this section has been removed.  Slice patterns were added to [the reference](https://doc.rust-lang.org/reference/patterns.html#rest-patterns) in https://github.com/rust-lang/reference/pull/876, which unfortunately isn't very friendly for beginners, but that's what we have for now.
