### ISSUE TITLE
Tracking issue for union improvements

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/edition-guide#173]
Rust tracking issues: https://github.com/rust-lang/rust/issues/32836 and https://github.com/rust-lang/rust/issues/55149 look relevant

Place that needs to be updated: https://github.com/rust-lang-nursery/edition-guide/blame/68c458b9b68edced39aebea60e672a22d4d50edf/src/rust-2018/data-types/union-for-an-unsafe-form-of-enum.md#L58-L60

> There’s still more improvements to come. For now, unions can only include `Copy` types and may not implement `Drop`. We expect to lift these restrictions in the future.

**Comment by ehuss** [comment]
Closing per #232, this section has been removed.  For now, I think the only documentation is in [the reference](https://doc.rust-lang.org/reference/items/unions.html), which should get updated whenever more work on unions is done.
