### ISSUE TITLE
Tracking issue for `std::simd`

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/edition-guide#174]
Rust tracking issue: https://github.com/rust-lang/rust/issues/27731

Place that needs to be updated: https://github.com/rust-lang-nursery/edition-guide/blame/68c458b9b68edced39aebea60e672a22d4d50edf/src/rust-2018/simd-for-faster-computing.md#L78-L81

> We hope to eventually stabilize a `std::simd` module with higher-level stuff in the future. But landing the basics now lets the ecosystem experiment with higher level libraries starting today.

**Comment by ehuss** [comment]
Closing per #232, this section has been removed.
