### ISSUE TITLE
Tracking issue for installing rust without docs via rustup

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/edition-guide#175]
Rustup tracking issue: https://github.com/rust-lang/rustup.rs/issues/998

If the ability to install without docs gets implemented, this spot will need to be updated: https://github.com/rust-lang-nursery/edition-guide/blame/68c458b9b68edced39aebea60e672a22d4d50edf/src/rust-2018/rustup-for-managing-rust-versions.md#L134-L136

> This component cannot be removed for now; if that's of interest, please
comment on [this issue](https://github.com/rust-lang-nursery/rustup.rs/issues/998).

**Comment by lzutao** [comment]
It is now possible with profile feature.

**Comment by ehuss** [comment]
Closing per #232, this section has been removed.

As mentioned, you can now skip docs with profiles.  And there is now a [rustup book](https://rust-lang.github.io/rustup/) with instructions on how to do various things.
