### ISSUE TITLE
Tracking issue for llvm-tools-preview becoming not preview or better documented

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/edition-guide#177]
Tracking issue: I don't see any tracking issue for what's keeping llvm-tools in preview status. This is where it was added: https://github.com/rust-lang/rust/issues/49584

Place that will need to be updated: https://github.com/rust-lang-nursery/edition-guide/blame/68c458b9b68edced39aebea60e672a22d4d50edf/src/rust-2018/rustup-for-managing-rust-versions.md#L207-L217

> #### `llvm-tools-preview` for using extra LLVM tools
>
> If you'd like to use the `lld` linker, or other tools like `llvm-objdump` or
`llvm-objcopy`, you can install this component:
>
> ```console
> $ rustup component add llvm-tools-preview
> ```
>
> This is the newest component, and so doesn't have good documentation at the
moment.

**Comment by ehuss** [comment]
Closing per #232, this section has been removed.  I have opened https://github.com/rust-lang/rust/issues/85658 to further track the `-preview` nature of the component, and to create some documentation for it.
