### ISSUE TITLE
Tracking issue for wasm-unknown-unknown

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/edition-guide#178]
Not sure about Rust issue, maybe https://github.com/rust-lang/rust/issues/44839 ?

Places that need to be updated:
- The nightly version at the top: https://github.com/rust-lang-nursery/edition-guide/blame/68c458b9b68edced39aebea60e672a22d4d50edf/src/rust-2018/platform-and-target-support/webassembly-support.md#L5
- This spot: https://github.com/rust-lang-nursery/edition-guide/blame/68c458b9b68edced39aebea60e672a22d4d50edf/src/rust-2018/platform-and-target-support/webassembly-support.md#L24-L28

> However, in the meantime, Rust has also grown its own support, independent from Emscripten. This is known as "the unknown target", because instead of `wasm32-unknown-emscripten`, it's `wasm32-unknown-unknown`. This will be the preferred target to use once it's ready, but for now, it's really only well-supported in nightly.

**Comment by ehuss** [comment]
Closing per #232, this section has been removed.  Indeed there isn't great documentation for targets.  Ideally I think that should live in the `rustc` book, and is something that has been on my todo list to get started for a while.
