### ISSUE TITLE
`dyn` could be explained better

### ISSUE THREAD

**Issue by knocte** [rust-lang/edition-guide#183]
There are two issues with this page: https://doc.rust-lang.org/edition-guide/rust-2018/trait-system/dyn-trait-for-trait-objects.html

It doesn't explain where does "dyn" come from, is it from the word "dynamic"? It should mention dynamic dispatching AFAIU.
It's targeted to people that are already familiar with Rust (that is, the people that were already using Rust before dyn keyword existed). If a new developer comes, it's better to just talk about the new way of doing things, not just mentioning that dyn is some new way to do some old stuff.

**Comment by Centril** [comment]
> It doesn't explain where does "dyn" come from, is it from the word "dynamic"? It should mention dynamic dispatching AFAIU.

Sure, a small note along with a link to the book would be good. I'd be happy to review such a PR.

>  It's targeted to people that are already familiar with Rust (that is, the people that were already using Rust before dyn keyword existed).

This is the intended target audience of the edition guide.

> If a new developer comes, it's better to just talk about the new way of doing things, not just mentioning that dyn is some new way to do some old stuff.

Seems like a better fit for the book.

**Comment by knocte** [comment]
> This is the intended target audience of the edition guide.

I was sent here from https://github.com/rust-lang/docs.rs/issues/374 , I guess I should reopen that one to have dyn docs that are not just related to editions?

> Seems like a better fit for the book.

What book? I found this issue by googling for "dyn rust" and not finding proper docs for a rust newbie.

**Comment by Centril** [comment]
> What book? I found this issue by googling for "dyn rust" and not finding proper docs for a rust newbie.

[The Rust Programming Language](https://github.com/rust-lang/book)

> I was sent here from [rust-lang/docs.rs#374](https://github.com/rust-lang/docs.rs/issues/374) , I guess I should reopen that one to have dyn docs that are not just related to editions?

The issue tracker for `docs.rs` (which collects docs about crates.io crates) is not the right place.

**Comment by knocte** [comment]
> The issue tracker for docs.rs (which collects docs about crates.io crates) is not the right place.

Holy cow this is a bit confusing. I'd suggest to rename docs.rs to cratedocs.rs, I don't know.

> The Rust Programming Language

So I open the issue there yeah? Yet another bounce :)

**Comment by Centril** [comment]
> So I open the issue there yeah? Yet another bounce :)

I'd still be open to improvements here as well. ^^

**Comment by ehuss** [comment]
Closing per #232, this section has been removed.  Sorry about getting bounced around, it can be confusing, and perhaps the edition guide didn't make its intended audience clear. 

Trait objects (and the `dyn` syntax) is usually first introduced in the book (https://doc.rust-lang.org/book/ch17-02-trait-objects.html) which discusses that it is used for dynamic dispatch.
