### ISSUE TITLE
Add a link in the docs theme for quickly editing the src on github

### ISSUE THREAD

**Issue by jeffwidman** [rust-lang/edition-guide#222]
I'm new to Rust and was poking around the docs and landed on the edition guide. I found a small typo, and wasn't sure where the source code for the edition guide was... although I eventually found it, it would have been much simpler if the site theme included a link straight to the source code for that particular page. 

This is common on ReadTheDocs, where it will have a link that says "edit on github" or a github icon or similar that I can click to immediately view the underlying source, make edits, and submit a PR.

**Comment by steveklabnik** [comment]
We would need mdbook to support this upstream. I don't know if it does or not.

**Comment by ehuss** [comment]
A link was added in #228 (the little GitHub icon in the upper-right corner).
