### ISSUE TITLE
[replace] is deprecated

### ISSUE THREAD

**Issue by digama0** [rust-lang/edition-guide#225]
https://github.com/rust-lang/edition-guide/blob/master/src/rust-2018/cargo-and-crates-io/replacing-dependencies-with-patch.md says "we don't intend to deprecate or remove [replace]" but [the cargo documentation](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-replace-section) says it is deprecated.

**Comment by ehuss** [comment]
Closing per #232, this section has been removed. Indeed, `[patch]` is preferred over `[replace]`.
