### ISSUE TITLE
Rust 2021 documentation for: Disjoint capture in closures (RFC 2229)

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/edition-guide#241]
- [x] Itemized summary
- [x] Initial details section (from blog post)
- [ ] Full description including edge cases and migration instructions (if relevant)

https://github.com/rust-lang/edition-guide/blob/master/src/rust-2021/disjoint-capture-in-closures.md

**Comment by nikomatsakis** [comment]
cc @rust-lang/wg-rfc-2229 -- it'd be great to take some of the material from that blog post draft and open a PR into this file.
