### ISSUE TITLE
Update guide to reference Rust 2021 when giving examples of editions in general

### ISSUE THREAD

**Issue by rylev** [rust-lang/edition-guide#257]
Where the guide talks about migrations and editions in general, it usually refers to Rust 2018. We should update these references to be Rust 2021 since the majority of readers will be coming for that edition. 

Of course, this needs to be timed for when the edition is stable. 

This is already at least partially addressed by https://github.com/rust-lang/edition-guide/pull/254 (which is waiting for stabilization before merging).

**Comment by m-ou-se** [comment]
Is there anything left to be done here?

**Comment by rylev** [comment]
There's still some work to do here. For example, [in the example migration](https://github.com/rust-lang/edition-guide/blob/2d9b1b9da706de24650fdc5c3b0182f55c82115d/src/editions/transitioning-an-existing-project-to-a-new-edition.md), the guide migrates from 2015 to 2018. Perhaps less urgent is that the [description of what editions are](https://github.com/rust-lang/edition-guide/blob/302a115e8f71876dfc884aebb0ca5ccb02b8a962/src/editions/index.md) uses only examples from Rust 2018.

**Comment by ehuss** [comment]
I intentionally left those as describing the 2018 changes.  Those changes are pretty clear and simple to describe.  Most of the migrations for 2021 are a bit more complicated, and I think could make it harder to understand.  I'd also like to avoid needing to update the text for every edition (particularly if future editions have migrations that are even harder to describe).  However, if you feel strongly about updating it, I won't object, but I probably won't change it myself.

**Comment by rylev** [comment]
@ehuss's justification seems reasonable to me. I took another look through the guide, and I'm sufficiently happy that it is in a good state for Rust 2021. As such I'm closing this issue.
