### ISSUE TITLE
A bunch of useful information about Rust 2018 is gone...

### ISSUE THREAD

**Issue by wa7sa34cx** [rust-lang/edition-guide#264]
There was a bunch of useful information about Rust 2018 in previous version. And I was still exploring it. Now, I can find this chapters only in Wayback Machine. It would be wise to keep the previous version under the RELEASES 🤔

**Comment by steveklabnik** [comment]
This is the way people wanted it, sadly, it is by design. Thanks though!

**Comment by ehuss** [comment]
All of the content is still available at https://doc.rust-lang.org/1.53.0/edition-guide/.  

For the most part, if you are exploring what is new or changed, the release blog posts at https://blog.rust-lang.org/ are also a good resource.  They try to highlight the major points.

There are redirects for all the old pages to documentation that covers what used to be in the edition guide (see the list [here](https://github.com/rust-lang/edition-guide/blob/3710b0cae783d0bcd2b42452a63b081473f5970a/book.toml#L10-L96)).  Most of them point to the blog posts which are a primary source of introducing new changes, but we also strive to make sure in-depth documentation lands somewhere when possible. Those might provide you pointers to where that documentation is.
