### ISSUE TITLE
Ambiguity rules for `use` have changed in Rust 1.72

### ISSUE THREAD

**Issue by mattheww** [rust-lang/edition-guide#284]
The following text at the end of `path-changes`

> If a path is ambiguous, such as if you have an external crate and a local module or item with the same name, you'll get an error, and you'll need to either rename one of the conflicting names or explicitly disambiguate the path.

is no longer true in Rust 1.72 (due to rust-lang/rust#112086).

I'm not sure whether the edition guide is only supposed to care about the behaviour with the latest compiler version.

**Comment by ehuss** [comment]
It is intended that the edition guide documents the behavior of the latest release. So if there are any changes that affect anything in the guide, the guide should be updated.

The edition-guide doesn't get as much attention or review of older content, so it is a little harder to keep it up-to-date. If people want to see historical behaviors, they can always visit the older documentation (like https://doc.rust-lang.org/1.72.0/edition-guide/). 

If you want to post a PR to fix it, I'd be happy to review it. And thanks for bringing it up!
