### ISSUE TITLE
Edition guide for 2024 tail expressions incorrectly imply it only affects drop order within a block, not outside it

### ISSUE THREAD

**Issue by kpreid** [rust-lang/edition-guide#342]
Location:
https://github.com/rust-lang/edition-guide/blob/4efbefa611258543294f77ee03643eb16800b399/src/rust-2024/temporary-tail-expr-scope.md

The current content of this page only talks about the drop order *within* a block, and gives an example of code that does not compile in 2021 but does in 2024. However, the 2021 rules allow temporaries to outlive the block into the enclosing expression, such as the `String` in the following program:

```rust
// compiles in 2021; fails in 2024
fn foo() {
    {
        &mut String::new()
    }.push_str("hello");
}
```

This program cannot be fixed merely by reordering or introducing variables within the affected block. This case should be documented in order to help users with situations such as https://github.com/rust-lang/rust/issues/134003. 

@rustbot label Edition-2024

**Comment by ehuss** [comment]
Thanks for the report! Yea, the chapter was pretty light and definitely could use some expansion. I have posted https://github.com/rust-lang/edition-guide/pull/345 to try to address this. There's probably still more that can be said, but it's a bit of a tricky topic to describe succinctly.

**Comment by kpreid** [comment]
Thanks for looking at this, @ehuss. Should this issue be labeled Edition-2024 for the record? I tried to do that but wasn't allowed. Could you do so if it is appropriate?
