### ISSUE TITLE
Translate this guide?

### ISSUE THREAD

**Issue by Centril** [rust-lang/edition-guide#87]
https://github.com/rust-lang-nursery/edition-guide/pull/86 gave me an idea... should we translate this guide?

It will probably need to be deferred until after most of it has stabilized so we don't need to update the translations all the time...

**Comment by tatsuya6502** [comment]
Just FYI, here is the repository we use for translating this guide into Japanese:
- https://github.com/rust-lang-ja/edition-guide

An rendered guide can be found here:
- https://doc.rust-jp.rs/edition-guide/

...though only the introduction has been translated so far.

> It will probably need to be deferred until after most of it has stabilized so we don't need to update the translations all the time...

Yeah. We will probably start with the pages for features that have been already released to the stable channel. I think they will not change very often.

* * *
cc: @tsraom

**Comment by ehuss** [comment]
Closing, as I don't think this should be tracked per-book.  This is a greater rust-lang org decision, and we have little tooling to support it. Of course the community is welcome to create and publish translations.
